# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: djangosaml2

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        django-version: ["3.2", "4.0", "4.1"]
        include:
        - python-version: "3.7"
          django-version: "3.2"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and testing utilities
      run: |
        sudo apt-get update && sudo apt-get install xmlsec1
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox rstcheck setuptools codecov
    #- name: Readme check
      #if: ${{ matrix.python-version }} == 3.8 && ${{ matrix.django-version }} == "3.0"
      #run: rstcheck README.rst
    - name: Tests
      run: tox -e py${{ matrix.python-version }}-django${{ matrix.django-version }}
